spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # For ephemeral DB in tests
  h2:
    console:
      enabled: true
logging:
  level:
    root: WARN
