logging:
  level:
    root: DEBUG
spring:
  datasource:
    url:
    driverClassName:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    url: jdbc:h2:mem:testdb
    user: sa
    password: password
    locations: classpath:db/migration